---
title: "Untitled"
author: "SOK-2011 Mappeoppgave"
format: pdf
editor: visual
---

```{r}
suppressPackageStartupMessages(library(WDI))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(plyr))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(countrycode))
suppressPackageStartupMessages(library(vtable))
suppressPackageStartupMessages(library(scales))
suppressPackageStartupMessages(library(ggthemes))
suppressPackageStartupMessages(library(sjPlot))
suppressPackageStartupMessages(library(sjmisc))
suppressPackageStartupMessages(library(sjlabelled))
```

### 2 Teori

```{r}

#  parametere
savings_rate <- 0.25
depreciation_rate <- 0.1
population_growth_rate <- 0.02
technology_growth_rate <- 0.01
alpha <- 0.3

# Definerer funksjoner 
production_per_eff_worker <- function(k) {
  k^alpha
}

steady_state_k <- function() {
  ((savings_rate) / (depreciation_rate + population_growth_rate + technology_growth_rate + population_growth_rate * technology_growth_rate))^(1 / (1 - alpha))
}

# 
k_vals <- seq(0, 10, 0.01)
y_vals <- production_per_eff_worker(k_vals)
investment_vals <- savings_rate * y_vals
depreciation_vals <- (depreciation_rate + population_growth_rate + technology_growth_rate) * k_vals

df <- data.frame(k = k_vals, y = y_vals, investment = investment_vals, depreciation = depreciation_vals)

# Plotter Solow-modellen 
ggplot(df, aes(x = k)) +
  geom_line(aes(y = investment), color = "red", linetype = "dashed") +
  geom_line(aes(y = depreciation), color = "black", linetype = "solid") +
  geom_vline(xintercept = steady_state_k(), color = "purple", linetype = "dashed", size = 1) +
  geom_text(aes(x = steady_state_k(), y = depreciation[100], label = "k'"), color = "purple", hjust = 1.3) + 
  geom_text(aes(x = 10, y = investment[100], label = "s * y"), color = "red", hjust = 1.2) +
  geom_text(aes(x = 10, y = depreciation[100], label = "n * k"), color = "black", hjust = 1.2) +
  labs(title = "Solow Model with steady state likevekt",
       x = "k",
       y = "sy,nk") +
  scale_x_continuous(breaks = NULL) + 
  scale_y_continuous( breaks = NULL) +
  theme_minimal()

```

### 3 Metode og data

```{r}
# 1. BNP per innbyggere (alle år) og initial nivå på BNP per innbyggere. WDI-variabel =  "NY.GDP.PCAP.PP.KD". 
# Velg startår = 2000 og sluttår = 2019
df_gdp0<-WDI(
  country = "all",
  indicator = c('gdppc'="NY.GDP.PCAP.PP.KD"),  
  start = 2000,
  end = 2019,
  extra = TRUE, # det å sette "extra = TRUE" fører til at vi laster inn ekstra informasjon som vi kan benytte seinere (f.eks. variabelen "region")
  cache = NULL,
  latest = NULL,
  language = "en"
)

df_gdp <- subset(df_gdp0, select = c(country, region, income, iso2c, iso3c, year, gdppc) ) %>%  arrange(iso3c, year) # velg ut relevante variabler
df_gdp <-  df_gdp %>% mutate_all(na_if,"") # Vi ønsker å ta vekk land som ikke har en iso3c kode. Dessverre er manglende observasjoner for "iso3c" (landkode) kodet som "blanks" isteden for "missing". Denne koden korrigerer dette.
df_gdp <- df_gdp[complete.cases( df_gdp$gdppc, df_gdp$iso3c),] # Ta vekk observasjoner som mangler data på gdppc og iso3c. 
df_gdp = df_gdp  %>%  
  mutate(year = as.numeric(year)) # Se til at year er en numerisk variabel. 

# Noen land har flere observasjoner for samme år (f.eks afghanistan år 2010). Vi ønsker å ha én observasjon per land og år. 
df_gdp <- df_gdp[!duplicated(df_gdp[c("iso3c", "year", max("gdppc"))]), ]  %>%  arrange(iso3c, year) # Ta vekk duplikater for land og år, behold observasjonen med størst gdppc (denne regelen kan diskuteres)

# Lag et datasett med Y0 (nivå på BNP per innbyggere i år 2000)
df_gdp2000  <- df_gdp %>%  arrange(iso3c, year) %>% group_by(iso3c) %>% #Behold den første observasjonen for BNP per innbyggere (Y0)
  slice(1) %>%
  ungroup()
df_gdp2000 = subset(df_gdp2000, select = -c(year) ) # Slett unødvendige variabler
df_gdp2000 <-   plyr:: rename(df_gdp2000,c("gdppc" = "gdppc0")) # Gi variabeln et nytt navn slik at vi kan identifisere den i datasetet. 

df_gdp <- left_join(df_gdp,df_gdp2000, by=c("country", "iso2c", "iso3c", "region", "income")) # Sett sammen data for BNP per innbygger alle år, med BNP per innbygger år 2000.
```

```{r}
# 2. Humankapital (gjennomsnittlig antall år i skole blant befolkningen eldre enn 15 år). WDI-variabel = BAR.SCHL.15UP 
df_educ0<-WDI(
  country = "all",
  indicator = c('educ'="BAR.SCHL.15UP"),  
  start = 2000,
  end = 2019,
  extra = TRUE,
  cache = NULL,
  latest = NULL,
  language = "en"
)

df_educ <- subset(df_educ0, select = c(country, region, income, iso2c, iso3c, year, educ) ) %>%  arrange(iso3c, year) #Behold nødvendige variabler
df_educ <- df_educ[complete.cases(df_educ$educ),] %>%  arrange(iso3c, year) # Slett observasjoner med manglende data

df_educ = df_educ %>%  
  arrange(iso3c, year) %>%  # Sorter etter Iso-kode og år. 
  mutate(educ = as.numeric(educ, na.rm = TRUE)) %>% # Se til at variabelen er numerisk
  ddply("iso3c",transform,
        avg_educ=mean(educ, na.rm = TRUE))  # Beregne gjennomsnittlig år i skole for tidsperioden 2000 - 2019 for hvert land, basert på tilgjenglig data (vil være 2000.2005,2010)

df_educ <- subset(df_educ, select = c(country, region, income, iso2c, iso3c, avg_educ)) # Her tar jeg vekk variabelen "year". Jeg gjør dette fordi vi bare har en observasjon på utdanning per land. Vi ønsker å bruke denne verdi for alle år. 
df_educ <- df_educ[!duplicated(df_educ[c("iso3c")]), ]  %>%  arrange(iso3c) # Ta vekk duplikater for hvert land.
```

```{r}
# 3. Gjennomsnittlig sparing for perioden 2000-2015 (lagg fordi det kan ta litt tid for sparing å bli til investering)
df_nsy0<-WDI(
  country = "all",
  indicator = c( 'nsy'="NY.ADJ.NNAT.GN.ZS"),  
  start = 2000,
  end = 2015,
  extra = TRUE,
  cache = NULL,
  latest = NULL,
  language = "en"
)

df_nsy <- subset(df_nsy0, select = c(country, region, income, iso2c, iso3c, year, nsy) ) %>%  arrange(iso3c, year) #Behold nødvendige variabler
df_nsy <- df_nsy[complete.cases(df_nsy$nsy),] %>%  arrange(iso3c, year) # Slett observasjoner med manglende data


df_nsy = df_nsy %>%  
  arrange(iso3c, year) %>%  # Sorter etter Iso-kode og år. 
  mutate(nsy = as.numeric(nsy, na.rm = TRUE)) %>% # Se til at variabelen er numerisk
  ddply("iso3c",transform,
        avg_nsy=mean(nsy, na.rm = TRUE))  # Beregne gjennomsnittlig år i skole for tidsperioden 2000 - 2019 for hvert land, basert på tilgjenglig data (vil være 2000.2005,2010)

df_nsy <- subset(df_nsy, select = c(country, region, income, iso2c, iso3c, avg_nsy)) # Her tar jeg vekk variabelen "year". Jeg gjør dette fordi vi bare har en observasjon på utdanning per land. Vi ønsker å bruke denne verdi for alle år. 
df_nsy <- df_nsy[!duplicated(df_nsy[c("iso3c")]), ]  %>%  arrange(iso3c) # Ta vekk duplikater for hvert land.
```

```{r}
# 4. Vekst i arbeidskraften (n)
df_lf0<-WDI(
  country = "all",
  indicator = c('lf'="JI.TLF.TOTL"),  # lf = labor force
  start = 2000,
  end = 2019,
  extra = TRUE, 
  cache = NULL,
  latest = NULL,
  language = "en"
)

df_lf <- subset(df_lf0, select = c(country, region, income, iso2c, year, lf) ) %>%  arrange(iso2c, year) # velg ut relevante variabler
df_lf <-   plyr:: rename(df_lf,c("iso2c" = "iso3c")) # variabelen som identifiserer land med kode er feil i datasetet. Dette korrigerer dette
df_lf <-  df_lf %>% mutate_all(na_if,"") 
df_lf [df_lf == 0]<-NA
df_lf <- df_lf[complete.cases(df_lf$iso3c, df_lf$lf),] # Ta vekk observasjoner som mangler data på lf og iso3c. 
df_lf = df_lf  %>%  
  mutate(year = as.numeric(year)) # Se til at year er en numerisk variabel. 

df_lf <- df_lf[!duplicated(df_lf[c("iso3c", "year")]), ]  %>%  arrange(iso3c, year) # Ta vekk duplikater for land og år

# Ta fram vekstraten i arbeidskraften (n). Vi har ikke data for hvert år i alle land. 
# For å beregne gjennomsnittlig årlig vekst må vi lage en variabel som måler antallet tidsperioder mellom hver observasjon.
df_n = df_lf %>%  
  arrange(iso3c, year) %>%  # Sorter på år og land
  ddply("iso3c",transform,
        t=c(NA,diff(year)),
        lf_growth=c(NA,diff(log(lf)))) #Vekstrate uten hensyn til tidsintervall

df_n <- df_n[complete.cases(df_n$t, df_n$lf_growth),] # Ta vekk observasjoner som mangler data på t

#Nå kan vi ta fram årlig vekstrate
df_n = df_n %>%  
        mutate(t = as.numeric(t)) %>%   
        mutate(lf_growth = as.numeric(lf_growth))
df_n <- transform(df_n, n =lf_growth/t)

# gjennomsnittlig vekstrate i arbeidskraften for hvert land
df_n <- df_n %>% # 
          ddply("iso3c",transform,
                avg_n=mean(n, na.rm = TRUE)) #Gjennomsnittlig årlig vekstrate i arbeidskraften

df_n <- subset(df_n, select = c(iso3c, avg_n) )
df_n <- df_n[!duplicated(df_n["iso3c"]), ]  %>%  arrange(iso3c) # Ta vekk duplikater for land
```

```{r}
# 5. Lag et datasett som inneholder BNP data, utdanningsdata, sparing, og arbeidskraftsdata

df <- left_join(df_gdp, df_educ, by=c("country", "iso2c", "iso3c", "region", "income"))
df <- left_join(df, df_nsy, by=c("country", "iso2c", "iso3c", "region", "income"))
df <- left_join(df, df_n, by="iso3c")
df <- subset(df, select = c(country, region, income, iso2c, iso3c, year, gdppc, gdppc0, avg_educ, avg_nsy, avg_n)) # Behold nødvendige variabler

# Mange observasjoner representerer aggregerte regioner. Vi ønsker å ta vekk disse. Det finnes helt sikkert en bedre måte å gjøre dette på. Dette er den måten jeg kom på.
df <- df  %>%  filter(iso2c!='1A' & iso2c !='1W' & iso2c != '4E' & iso2c != '7E' & iso2c !='8S'
                                         & iso2c !='B8' & iso2c !='EU' & iso2c !='F1' & iso2c !='OE' & iso2c !='S1' & iso2c !='S2' & iso2c !="S3" 
                                         & iso2c !='S4' & iso2c !='T2' & iso2c !='T3' & iso2c !='T4' & iso2c !='T5' & iso2c !='T6' & iso2c !='T7' 
                                         & iso2c !='V1' & iso2c !='V2' & iso2c !='V3' & iso2c !='V4' & iso2c !='XC' & iso2c !='XD' & iso2c !='XE' 
                                         & iso2c !='XF' & iso2c !='XG' & iso2c !='XH' & iso2c !='XI' & iso2c !='XJ' & iso2c !='XL' & iso2c !='XM' 
                                         & iso2c !='XN' & iso2c !='XO' & iso2c !='XP' & iso2c !='XQ' & iso2c !='XT' & iso2c !='XU' & iso2c !='Z4' 
                                         & iso2c !='Z7' & iso2c !='ZF'& iso2c !='ZG'  & iso2c !='ZH' & iso2c !='ZI'  & iso2c !='ZJ'  & iso2c !='ZQ'  
                                         & iso2c !='ZT'  & iso2c !='Z7')  %>% arrange(iso3c, year) 
```

```{r}
# 6. Lag et datasett for resterende variabler.

df_rest0<-WDI(
  country = "all",
  indicator = c('poptot'="SP.POP.TOTL", 'gi'="NE.GDI.FTOT.KD.ZG", 'gx'="NE.EXP.GNFS.KD.ZG", 'nry'="NY.ADJ.DRES.GN.ZS", 'p'="SP.POP.GROW" ),  
  start = 2000,
  end = 2019,
  extra = TRUE,
  cache = NULL,
  latest = NULL,
  language = "en"
)

df_rest0<-df_rest0 %>% mutate_all(na_if,"")
df_rest <- df_rest0[complete.cases( df_rest0$iso3c),]  %>%  arrange(iso2c) 


# Ta vekk observasjoner som ikke representerer land.
df_rest <- df_rest  %>%  filter(iso2c!='1A' & iso2c !='1W' & iso2c != '4E' & iso2c != '7E' & iso2c !='8S'
                                  & iso2c !='B8' & iso2c !='EU' & iso2c !='F1' & iso2c !='OE' & iso2c !='S1' & iso2c !='S2' & iso2c !="S3" 
                                  & iso2c !='S4' & iso2c !='T2' & iso2c !='T3' & iso2c !='T4' & iso2c !='T5' & iso2c !='T6' & iso2c !='T7' 
                                  & iso2c !='V1' & iso2c !='V2' & iso2c !='V3' & iso2c !='V4' & iso2c !='XC' & iso2c !='XD' & iso2c !='XE' 
                                  & iso2c !='XF' & iso2c !='XG' & iso2c !='XH' & iso2c !='XI' & iso2c !='XJ' & iso2c !='XL' & iso2c !='XM' 
                                  & iso2c !='XN' & iso2c !='XO' & iso2c !='XP' & iso2c !='XQ' & iso2c !='XT' & iso2c !='XU' & iso2c !='Z4' 
                                  & iso2c !='Z7' & iso2c !='ZF'& iso2c !='ZG'  & iso2c !='ZH' & iso2c !='ZI'  & iso2c !='ZJ'  & iso2c !='ZQ'  
                                  & iso2c !='ZT'  & iso2c !='Z7')  %>% arrange(iso3c, year) 

df_rest <- subset(df_rest, select = c("country", "region", "income", "iso3c", "iso2c", "year", "poptot", "p", "nry", "gi", "gx"))
df_all <- left_join(df, df_rest, by=c("country", "region", "income", "iso2c", "iso3c", "year"))

# Lag en rekkefølge til variablene slik at det er enklere å få en oversikt over datamaterialet.
col_order <- c("country",  "region", "income", "iso3c", "iso2c", "year", "gdppc", "gdppc0", "poptot", "p", "avg_n", "avg_nsy", "nry", "gi", "gx", "avg_educ")
df_all <- df_all[, col_order]
```

```{r}
# Ta fram vekstraten og gjennomsnitt for resterende variabler
df_growth0 = df_all %>%  
  arrange(iso3c, year) %>%  # Sorter på år og land
  ddply("iso3c",transform,
        gdpgrowth=c(NA,diff(log(gdppc)))*100) %>%   # Årlig vekstrate i gdppc for hvert land
  mutate(gdpgrowth = as.numeric(gdpgrowth, na.rm = TRUE)) %>% # 
  ddply("iso3c",transform,
        avg_gdpgrowth=mean(gdpgrowth, na.rm = TRUE), #Gjennomsnittlig årlig vekstrate i BNP per innbygger for hvert land i perioden
        avg_gi=mean(gi, na.rm = TRUE), # Gjennomsnittlig årlig vekstrate i investeringer for hvert land  i perioden
        avg_nry=mean(nry, na.rm = TRUE),  # Gjennomsnittlig årlig vekstrate (negativ) i naturressurser for hvert land  i perioden
        avg_gx=mean(gx, na.rm = TRUE),  # Gjennomsnittlig årlig vekstrate i eksport for hvert land  i perioden
        avg_p=mean(p, na.rm = TRUE))  # Gjennomsnittlig årlig vekstrate i befolkningen for hvert land  i perioden
        
#View(df_growth0)
df_growth0 <-  df_growth0 %>% mutate_all(na_if,"") 
df_growth <- df_growth0[complete.cases( df_growth0$country, df_growth0$income, df_growth0$iso3c, df_growth0$avg_gdpgrowth, df_growth0$gdppc0, df_growth0$avg_n, df_growth0$avg_p, df_growth0$avg_nsy, df_growth0$avg_nry,df_growth0$avg_gi, df_growth0$avg_gx, df_growth0$avg_educ),] # Ta vekk land som mangler data 


df_growth <- subset(df_growth, select = c("country",  "region", "income", "iso3c", "iso2c","year", "poptot", "gdppc", "gdppc0", "avg_gdpgrowth", "avg_n", "avg_p", "avg_nsy", "avg_nry", "avg_gi", "avg_gx", "avg_educ"))

# Lage datasettet du vil bruke til analysen din
df_growth2019  <- df_growth %>%  arrange(iso3c, year) %>% group_by(iso3c) %>% 
  slice(n()) %>% # Behold den SISTE observasjonen for hvert land
  ungroup()
head(df_growth2019)
```

```{r}
# Lag en variabel som er logaritmen av BNP per innbygger (enklere tolkning og presser sammen fordelingen)
df_growth2019$dppc <-as.numeric(df_growth2019$gdppc)
df_growth2019$ln_gdppc<-log(df_growth2019$gdppc) 
df_growth2019$ln_gdppc0<-log(df_growth2019$gdppc0) 
```

## **4. Resultat**

\
**4.1 Deskriptiv statistikk**

```{r}
# Velg ut de variabler du vil ha med i tabellen. Her er et eksempel (du skal ta med alle variabler som du har med i den empiriske analysen)
df <- subset(df_growth2019, select = c("avg_gdpgrowth", "avg_p", "avg_educ", "avg_nsy", "avg_nry", "avg_gi", "avg_gx", "avg_n"))

# Gi beskrivende navn til variablene (i samme rekkefølge som de ligger i datasettet)
labs <- c("Gjennomsnitlig aarlig vekstrate i BNP pc 2000-2019 (%)", "Gjennomsnittlig aarlig befolkningsvekst (%)", "Gjennomsnittlig aarlig utdanning", "Gjennomsnittlig aarlig spare rate", "Gjennomsnittlig aarlig reduksjon i naturressurser", "Gjennomsnittlig aarlig vekst i investering", "Gjennomsnittlig aarlig vekstrate for eksport", "Gjennomsnittlig aarlig vekstrate i arbeidskraft (%)") 

# Lag tabellen
st(df, labels=labs,
   summ = list(
     c('notNA(x)','mean(x)','sd(x)','min(x)','max(x)'), # Beskriv hvilken statistikk du ønsker å vise
     c('notNA(x)','mean(x)')
   ),
   summ.names = list(
     c('N','Gjennomsnitt','SD','Min','Maks') # Gi navn til kolumnene
  ))
```

```{r}
df_growth2019_n <- df_growth2019[complete.cases(df_growth2019$region,df_growth2019$poptot, df_growth2019$avg_p, df_growth2019$gdppc),] #Her tar jeg vekk land som mangler observasjoner. Dette gjør grafen penere.  
```

```{r}
plot1 <- ggplot(df_growth2019_n, aes(x = avg_nsy, y = ln_gdppc , na.rm = TRUE)) +
  xlab("Sparerate") +
  ylab("BNP per innbygger") +
  theme_minimal(base_size = 14, base_family = "Georgia") +
  geom_point(aes(size = poptot, color = region), alpha = 0.6) +
  scale_size_area(guide = "none", max_size = 14) +
  theme(legend.text = element_text(size = 10, color = "black")) +
  scale_colour_brewer(palette = "Set2") +
  labs(title = "BNP per innbygger og sparerate",
       subtitle = "Størrelsen på punktene representerer befolkningens størrelse") +
  theme(plot.title = element_text(hjust = 0.5, size = 14, face = "bold"),
        plot.subtitle = element_text(hjust = 0.5, size = 8)) +
  theme(panel.grid.major = element_line(colour = "gray90", size = 0.2),
        panel.grid.minor = element_line(colour = "gray95", size = 0.1),
        panel.background = element_rect(fill = 'white', color = "gray90")) +
  scale_y_continuous(breaks = seq(-10, 40, by = 5)) +
  scale_x_continuous(breaks = seq(0, 60, by = 5)) + 
  geom_smooth(method = "lm", se = FALSE, color = "red")
plot1

```

```{r}
plot2 <- ggplot(df_growth2019_n, aes(x = avg_educ, y = ln_gdppc , na.rm = TRUE)) +
  xlab("Årlig utdanning ") +
  ylab("BNP per innbygger") +
  theme_minimal(base_size = 14, base_family = "Georgia") +
  geom_point(aes(size = poptot, color = region), alpha = 0.6) +
  scale_size_area(guide = "none", max_size = 14) +
  theme(legend.text = element_text(size = 10, color = "black")) +
  scale_colour_brewer(palette = "Set2") +
  labs(title = "BNP per innbygger og årlig utdanning",
       subtitle = "Størrelsen på punktene representerer befolkningens størrelse") +
  theme(plot.title = element_text(hjust = 0.4, size = 14, face = "bold"),
        plot.subtitle = element_text(hjust = 0.5, size = 8)) +
  theme(panel.grid.major = element_line(colour = "gray90", size = 0.2),
        panel.grid.minor = element_line(colour = "gray95", size = 0.1),
        panel.background = element_rect(fill = 'white', color = "gray90")) +
  scale_y_continuous(breaks = seq(-10, 40, by = 1)) +
  scale_x_continuous(breaks = seq(0, 60, by = 5)) +
  geom_smooth(method = "lm", se = FALSE, color = "red")
plot2
```

```{r}
plot3 <- ggplot(df_growth2019_n, aes(x = avg_p, y = ln_gdppc, na.rm = TRUE)) +
  xlab("Befolkningsvekst") +
  ylab("BNP per innbygger") +
  theme_minimal(base_size = 14, base_family = "Georgia") +
  geom_point(aes(size = poptot, color = region), alpha = 0.6) +
  scale_size_area(guide = "none", max_size = 14) +
  theme(legend.text = element_text(size = 10, color = "black")) +
  scale_colour_brewer(palette = "Set2") +
  labs(title = "BNP per innbygger og befolkningsvekst",
       subtitle = "Størrelsen på punktene representerer befolkningens størrelse") +
  theme(plot.title = element_text(hjust = 0.5, size = 14, face = "bold"),
        plot.subtitle = element_text(hjust = 0.5, size = 8)) +
  theme(panel.grid.major = element_line(colour = "gray90", size = 0.2),
        panel.grid.minor = element_line(colour = "gray95", size = 0.1),
        panel.background = element_rect(fill = 'white', color = "gray90")) +
  scale_y_continuous(breaks = seq(-10, 40, by = 1)) +
  scale_x_continuous(breaks = seq(0, 60, by = 1)) +
  geom_smooth(method = "lm", se = FALSE, color = "red")
plot3
```

```{r}
plot4 <- ggplot(df_growth2019_n, aes(x = avg_educ, y = avg_gdpgrowth, na.rm = TRUE)) +
  xlab("Utdanning") +
  ylab("Vekst i BNP per innbygger") +
  theme_minimal(base_size = 14, base_family = "Georgia") +
  geom_point(aes(size = poptot, color = region), alpha = 0.6) +
  scale_size_area(guide = "none", max_size = 14) +
  theme(legend.text = element_text(size = 10, color = "black")) +
  scale_colour_brewer(palette = "Set2") +
  labs(title = "Vekst i BNP per innbygger og utdanning",
       subtitle = "Størrelsen på punktene representerer befolkningens størrelse") +
  theme(plot.title = element_text(hjust = 0.5, size = 14, face = "bold"),
        plot.subtitle = element_text(hjust = 0.5, size = 8)) +
  theme(panel.grid.major = element_line(colour = "gray90", size = 0.2),
        panel.grid.minor = element_line(colour = "gray95", size = 0.1),
        panel.background = element_rect(fill = 'white', color = "gray90")) +
  scale_y_continuous(breaks = seq(-10, 40, by = 5)) +
  scale_x_continuous(breaks = seq(0, 60, by = 5)) +
  geom_smooth(method = "lm", se = FALSE, color = "red")
plot4
```

```{r}
plot5 <- ggplot(df_growth2019_n, aes(x = avg_nsy, y = avg_gdpgrowth, na.rm = TRUE)) +
  xlab("Sparereate") +
  ylab("Vekst i BNP per innbygger") +
  theme_minimal(base_size = 14, base_family = "Georgia") +
  geom_point(aes(size = poptot, color = region), alpha = 0.6) +
  scale_size_area(guide = "none", max_size = 14) +
  theme(legend.text = element_text(size = 10, color = "black")) +
  scale_colour_brewer(palette = "Set2") +
  labs(title = "Sparing og vekst i BNP",
       subtitle = "Størrelsen på punktene representerer befolkningens størrelse") +
  theme(plot.title = element_text(hjust = 0.5, size = 14, face = "bold"),
        plot.subtitle = element_text(hjust = 0.5, size = 8)) +
  theme(panel.grid.major = element_line(colour = "gray90", size = 0.2),
        panel.grid.minor = element_line(colour = "gray95", size = 0.1),
        panel.background = element_rect(fill = 'white', color = "gray90")) +
  scale_y_continuous(breaks = seq(-10, 40, by = 5)) +
  scale_x_continuous(breaks = seq(0, 60, by = 5)) +
  geom_smooth(method = "lm", se = FALSE, color = "red")
plot5
```

\
**4.2 Økonometrisk analyse**

```{r}
reg_model1 <- lm(avg_gdpgrowth ~ avg_gi + avg_n + avg_educ, data = df_growth2019)

# Vis resultater
tab_model(
  reg_model1, 
  pred.labels = c("Intercept", "Årlig vekstrate i investeringer", "Gjennomsnittlig årlig vekstrate i arbeidskraft", "Gjennomsnittlig antall år i skole"),
  dv.labels = c("Regresjon 1"),
  string.pred = "Coeffcient",
  string.ci = "Conf. Int (95%)",
  string.p = "P-Value"
)
```

```{r}
reg_model2 <- lm(avg_gdpgrowth ~  avg_nsy + avg_educ + avg_nry + avg_gi + avg_gx + avg_n + avg_p + ln_gdppc0, data = df_growth2019)

# Vis resultater
tab_model(
  reg_model2, 
  pred.labels = c("Intercept", "Sparing som andel av BNI", "Gjennomsnittlig antall år i skole", "Årlig reduksjonsrate i naturressurser", "Årlig vekstrate i investeringer", "Årlig vekstrate i eksport", "Gjennomsnittlig årlig vekstrate i arbeidskraft", "Vekstrate i befolkningen", "BNP per innbygger i 2000"),
  dv.labels = c("Regresjon 2"),
  string.pred = "Coeffcient",
  string.ci = "Conf. Int (95%)",
  string.p = "P-Value"
)
```

```{r}
df <- df_growth2019[complete.cases( df_growth2019$avg_gi, df_growth2019$avg_n),]

Q1gi <- quantile(df$avg_gi, .25 )
Q3gi <- quantile(df$avg_gi, .75)
IQRgi <- IQR(df$avg_gi)

Q1n <- quantile(df$avg_n, .25 )
Q3n <- quantile(df$avg_n, .75)
IQRn <- IQR(df$avg_n)

no_outliers <- subset(df, df$avg_gi > (Q1gi - 1.5*IQRgi) & df$avg_gi < (Q3gi + 1.5*IQRgi) &  df$avg_n > (Q1n - 1.5*IQRn) & df$avg_n < (Q3n + 1.5*IQRn))
dim(no_outliers)
```

```{r}
reg_model3 <- lm(avg_gdpgrowth ~ avg_gi + avg_n + avg_educ, data = no_outliers)

# Vis resultater
tab_model(
  reg_model3, 
  pred.labels = c("Intercept", "Årlig vekstrate i investeringer", "Gjennomsnittlig årlig vekstrate i arbeidskraft", "Gjennomsnittlig antall år i skole"),
  dv.labels = c("Regresjon 1 uten outliers"),
  string.pred = "Coeffcient",
  string.ci = "Conf. Int (95%)",
  string.p = "P-Value"
)
```

```{r}
reg_model4 <- lm(avg_gdpgrowth ~ avg_nsy + avg_educ + avg_nry + avg_gi + avg_gx + avg_n + avg_p + ln_gdppc0, data = no_outliers)

# Vis resultater
tab_model(
  reg_model4, 
  pred.labels = c("Intercept", "Sparing som andel av BNI", "Gjennomsnittlig antall år i skole", "Årlig reduksjonsrate i naturressurser", "Årlig vekstrate i investeringer", "Årlig vekstrate i eksport", "Gjennomsnittlig årlig vekstrate i arbeidskraft", "Vekstrate i befolkningen", "BNP per innbygger i 2000"),
  dv.labels = c("Regresjon 2 uten outliers"),
  string.pred = "Coeffcient",
  string.ci = "Conf. Int (95%)",
  string.p = "P-Value"
)
```
